[Definition]
actionstart = iptables -I DOCKER-USER -j RETURN
actionstop =
actioncheck =
actionban = iptables -I DOCKER-USER 1 -s <ip> -j DROP
actionunban = iptables -D DOCKER-USER -s <ip> -j DROP

[Init]
name = default
