access_log /var/log/nginx/access.log;
error_log /var/log/nginx/error.log warn;

server {
    listen 80;
    server_name testohsal.com www.testohsal.com;

    location /test/ {
        alias /var/www/certbot;
        index index.html;
        try_files /index.html =404;
    }

    # ACME challenge path for Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}
